"""rename department

Revision ID: 318a4315c47e
Revises: bf52a783bbc6
Create Date: 2025-01-08 16:00:06.507246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '318a4315c47e'
down_revision = 'bf52a783bbc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
